alsa: Update to version 1.2.15.3
- Update from version 1.2.15.1 to 1.2.15.3
- Update of rootfile
- Changelog
    1.2.15.3
	alsa-lib
		Sequencer API
		    seq: return back old snd_seq_drain_output behaviour for -EAGAIN
	alsa-ucm-conf
		Configuration
		    HDA-analog: Fix the phantom jack detection if block
		    HDA-analog: Use phantom jacks to determine the device for single
			output
		    HDA-analog: Add output when only 'Master Playback' control exists
		    sof-hda-dsp: remove some debug lines
		    sof-hda-dsp: Headphone output is optional
		    ucm2: HDA: Fix headphone detection
		    USB-Audio: Add volume controls to Behringer UMCx0xHD direct profiles
		    USB-Audio: Fix UR22C firmware version condition
		    USB-Audio: Add support for UR24C firmware version channel differences
    1.2.15.2
	alsa-lib
		Use Case Manager API
		    ucm: add some traces for the config filenames
		Makefile.am
		    Makefile: remove dist-hook and remove tar option 'follow symlinks'
		Error handler
		    error: fix the "return old snd_lib_error_set_handler() behaviour"
		    error: fix indendation in snd_lib_log_filter()
		    error: return old snd_lib_error_set_handler() behaviour
	alsa-utils
		ALSA Control (alsactl)
		    alsactl: fix sequence to clean card specific config files for UCM
		    alsactl: add missing call to clean card specific config files
		alsaloop
		    alsaloop: only log xrun debug messages when verbose
		aplay/arecord
		    aplay: add support for G.711 A_LAW enconding in AU file format
	alsa-ucm-conf
		Configuration
		    common: remove direct.conf and direct-verb.conf files
		    USB-Audio: update to use new DirectUseCase macro
		    common: introduce DirectUseCase macro
		    USB-Audio: Scarlett 18i20 gen4 - improve channel detection
		    USB-Audio: Add conditional channel count on Scarlett 18i20 version
		    USB-Audio: Steinberg UR22C - fix regex
		    ucm2: HDA: Create microphone devices optionally
		    ucm2: HDA: Headphone output may be optional
		    ucm2: sof-soundwire: cs42l45: Remove outdated DisableSequence
			elements
		    ucm2: sof-soundwire: cs42l43: Remove outdated DisableSequence
			elements

Signed-off-by: Adolf Belka <adolf.belka@ipfire.org>
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>